// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Simulator.Models;

#nullable disable

namespace Simulator.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20250228045428_AddProductionPlanTable")]
    partial class AddProductionPlanTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductionPlanManagement.Models.ProductionPlan", b =>
                {
                    b.Property<string>("DeliveryDate")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Line")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PalletNumber")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Hinban")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeliveryDate", "Line", "PalletNumber", "Priority", "Size");

                    b.HasIndex("DeliveryDate", "Line", "PalletNumber", "Size");

                    b.ToTable("ProductionPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
